# Generated by Django 5.0.6 on 2024-06-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="date_added",
        ),
    ]
