# Generated by Django 5.0.6 on 2024-06-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_item_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_added",
            field=models.DateField(null=True),
        ),
    ]
